### PR TITLE
Update multiQC to 0.9

### PR DESCRIPTION
**Pull request by dpryan79**
This PR updates the version of multiQC used to 0.9, switches to conda dependency resolution (you can get rid of the package if you want) and adds support for a large number of additional inputs.

BTW, I added support for travisCI testing (it runs all of the tests with planemo), in case you'd like to use it.

### CODE REVIEW

**Comment by dpryan79** [comment]
BTW, the conda dependency resolution stuff will fix #1, #2, and #4.

**Comment by ewels** [comment]
Nice work! Note that I'm hoping to release v1.0 of MultiQC pretty soon (next week if everything goes to plan).

**Comment by dpryan79** [comment]
Figures :open_mouth: On the plus side, this will go a long way to getting a better 1.0 in Galaxy :)

Is 1.0 coming from the `master` branch? If so, I'll just base stuff off of that and pull this PR until you release.

**Comment by ewels** [comment]
Sorry! Better to know now than just _after_ you push this I guess 😉 

Yes it will come off the `master` branch, so shouldn't vary too much from that. Note that there are a few breaks in backwards compatibility on this release - though hopefully none that will affect you. See the [changelog](https://github.com/ewels/MultiQC/blob/master/CHANGELOG.md#v10dev) for more.

Phil

**Comment by dpryan79** [comment]
Does the `multiqc_data/.multiqc.log` file still get made? In all of the Galaxy tests that's 0 bytes in version 1.0dev0. That should be an optional output in Galaxy anyway.

**Comment by dpryan79** [comment]
Otherwise, a quick update of the html used in the tests and the Galaxy wrapper will be ready for 1.0 :)

I'll close this until 1.0 comes out.

**Comment by ewels** [comment]
Yes it's still there, but it's lost the hidden dot so it's now called `multiqc_data/multiqc.log`

**Comment by dpryan79** [comment]
Ah, that explains that, thanks!

**Comment by dpryan79** [comment]
@ewels Are you still expecting to push out 1.0 soonish? I noticed that the issues on the 1.0 milestone recently grew a bit...

**Comment by ewels** [comment]
Yes, sorry - it's been a busy week and I've been distracted with other tasks a few times (we had a AWS conference in Stockholm which got me excited). I need to spend a day working on the front-end issues that I'd like to fix before release, and then I'll hit go. I'll try to make that day next week, Monday if all goes to plan...

Phil

**Comment by ewels** [comment]
Hi @dpryan79,

Apologies for the delay, getting the last things finished always takes longer than I expect! MultiQC v1.0 now released: https://github.com/ewels/MultiQC/releases/tag/v1.0

Phil

**Pull request closed without merging**
