### PR TITLE
made help more readable and fixed sed syntax in command line

### PR DESCRIPTION
**Pull request by nekrut**
@yvanlebras @cmonjeau @dpryan79 thank you for wrapping this tool. Would you be okay with moving this tool into IUC (I can do that, if it is ok), so we can have it deployed at usegalaxy.org?

### CODE REVIEW

**Comment by dpryan79** [comment]
@nekrut I was about to check if the toolshed had been updated, thanks for saving me the trouble :)

**Comment by nekrut** [comment]
nope, I think the TS version uses conda version 0.6

**Comment by ewels** [comment]
Hi both - I'm not sure how you're using conda, but it may be worth warning that the current v1.0 release on conda is currently python 2.7 only. There's a problem with one of the libraries in the current build environment for py3 which we're working on. I hope this is ok!

Phil

**Comment by dpryan79** [comment]
@ewels This won't be the first python2 only package in Galaxy (MACS2 is also python2 only and it's on usegalaxy.org).

**Comment by ewels** [comment]
Sure, but MultiQC runs on just about any version of python above 2.7... It's just the conda distribution that's broken :(

**Comment by nekrut** [comment]
@ewels this should be ok from galaxy's standpoint. We should have it at usegalaxy.org soon!

**Pull request merged**
